services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  zipline:
    build:
      context: .
      dockerfile: Dockerfile
    # UNCOMMENT THE BELOW LINE ON THE FIRST RUN!
    entrypoint: ['pnpm', 'db:prototype']
    # entrypoint: ['pnpm', 'prisma', 'migrate', 'reset', '--force']
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/postgres
      - CORE_SECRET=thissecretisverynotsecretbutshouldonlybeusedindevelopmentsoitsfineiguess
      - CORE_HOSTNAME=0.0.0.0
    depends_on:
      - postgres
    volumes:
      - './uploads:/zipline/uploads'
      - './public:/zipline/public'
      - './themes:/zipline/themes'

volumes:
  pgdata:
